package com.example.uboatvault.api.model.persistence.sailing;

public enum Stage {
    ESTABLISHING_CONNECTION, SAILOR_DENIED, SAILOR_ACCEPTED, VERIFYING_PAYMENT, PAYMENT_ACCEPTED, TOWARDS_CLIENT, SAILING, FINISHED, ERROR
}
