server:
  port: 8083
  error:
    include-message: always
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uboat_vault
    username: uboat
    password: uboat

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

uboat:
  max-active-seconds: 300
  max-active-sailors: 5
  hs256_key: key1234