whitelist:
  /v3/api-docs/**,
  /v3/api-docs.yaml,
  /v3/api-docs,
  /swagger-ui/**,
  /swagger-ui,
  /favicon.ico,
  /api/phoneNumber,
  /api/email,
  /api/username,
  /api/deviceRegistration,
  /api/jwt,
  /api/requestRegistration,
  /api/registrationSms,
  /api/emailVerification,
  /api/register,
  /api/login

client-blacklist:
  /api/boat,
  /api/sailor/**

sailor-blacklist:
  /api/sailorDetails,
  /images/sailorProfilePicture,
  /api/client/**

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

uboat:
  pretty-print-logs: false
  apis-body-not-logged:
    /images/defaultProfilePicture,
    /images/profileImage,
    /images/sailorProfilePicture,
    /images/boatImage

  regex: # place regex on the second row
    phone: >-
      ^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$
    email: >-
      ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$$
    username: >-
      ^[a-zA-z][a-zA-z0-9]*$
    password: >-
      ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$
