server:
  port: ${PORT}
  error:
    include-message: always
    whitelabel:
      enabled: false

spring:
  security:
    user:
      name: UBoat
      password: cae85770-9aa3-46c3-a492-9406c930d00c

  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${DDL_AUTO}

uboat:
  max-active-seconds: 300
  max-active-sailors: 5
  hs256_key: key1234