whitelist:
  /v3/api-docs/**,
  /v3/api-docs.yaml,
  /v3/api-docs,
  /swagger-ui/**,
  /swagger-ui,
  /favicon.ico,
  /api/isVaultActive,
  /api/checkUsername,
  /api/checkPhoneNumber,
  /api/checkDeviceRegistration,
  /api/verifyJsonWebToken,
  /api/requestRegistration,
  /api/register,
  /api/login

client-blacklist:
  /api/getMyBoat,
  /api/updateMyBoat,
  /images/uploadBoatImage

sailor-blacklist:
  /api/getSailorDetails,
  /images/getSailorProfilePicture

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

uboat:
  pretty-print-logs: false