server:
  port: 8083
  error:
    include-message: always
    whitelabel:
      enabled: false
  address: 192.168.0.192

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uboat_vault
    username: uboat
    password: uboat

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

uboat:
  pretty-print-logs: true
  max-active-seconds: 300
  max-active-sailors: 5
  max-accepted-distance: 100000
  
  schedulersCron:
    clientScheduler:
      deleteInactiveInitiatedJourneys: "*/30 */1 * * * *"
      initiatedJourneyExpirationSeconds: 90

    sailorScheduler:
      assertSailorsAreActive: "*/30 * * * * *"

    journeyScheduler:
      removeJourneysNotConfirmed: "*/30 * * * * *"
      journeysNotConfirmedTimeoutSeconds: 60
      checkNoActivityJourneys: "* */1 * * * *"
      checkNoActivityJourneysTimeoutSeconds: 600 # 10 minutes

  hs256_key: key1234