package com.uboat.vault.api.model.persistence.sailing;

public enum Stage {
    ESTABLISHING_CONNECTION, CANCELED, SAILOR_ACCEPTED, VERIFYING_PAYMENT, PAYMENT_ACCEPTED, TOWARDS_CLIENT, SAILING, FINISHED, ERROR
}
