package com.uboat.vault.api.model.enums;

public enum Stage {
    CLIENT_ACCEPTED, CLIENT_CANCELED,
    SAILOR_ACCEPTED, SAILOR_CANCELED,

    VERIFYING_PAYMENT, PAYMENT_ACCEPTED,

    SAILING_TO_CLIENT, SAILING_TO_DESTINATION,

    FINISHED, ERROR
}
